[package]
name = "containerd-shim-wasm"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
containerd-shim = { git = "https://github.com/utam0k/rust-extensions", branch="runwasi" }
containerd-shim-protos = "0.1"
anyhow = "1.0"
serde_json = "1.0"
oci-spec = "0.5"
command-fds = "0.2"
serde = "1.0"
thiserror = "1.0"
protobuf = "2.23"
ttrpc = "0.6"
nix = "0.25"
cap-std = "0.24"
chrono = "0.4"
log = "0.4"
clone3 = "0.2"
libc = "0.2"
caps = "0.1"
proc-mounts = "0.3"

[build-dependencies]
ttrpc-codegen = { version = "0.3", optional = true }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"
signal-hook = "0.3"

[features]
default = []
generate_bindings = ["ttrpc-codegen"]
