[package]
name = "oci-tar-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
tar = "0.4"
sha256 = "1.1"
log = "0.4"
env_logger = "0.10"
oci-spec =  "0.5"
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"